AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs12.x
    Timeout: 10

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join ["-", [!Ref ProjectName, !Ref Environment, users]]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Join ["-", [!Ref ProjectName, client]]
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      ReadAttributes:
        - email
        - email_verified
        - name
      WriteAttributes:
        - email
        - name

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join ["-", [!Ref ProjectName, !Ref Environment]]

  TransadminApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
          - GET
          - PUT
          - DELETE
        AllowHeaders:
          - "*"
      Auth:
        Authorizers:
          Cognito:
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              audience:
                - !Ref UserPoolClient
            IdentitySource: $request.header.Authorization
      FailOnWarnings: true
      StageVariables:
        NOTES_TABLE: !Ref NotesTable

  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["-", [!Ref ProjectName, !Ref Environment, notes]]
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  NotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["-", [!Ref ProjectName, !Ref Environment, notes]]
      CodeUri: functions/notes
      Events:
        Create:
          Type: HttpApi
          Properties:
            ApiId: !Ref TransadminApi
            Method: POST
            Path: /notes
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref TransadminApi
            Method: GET
            Path: /notes
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref TransadminApi
            Method: GET
            Path: /notes/{id}
        Update:
          Type: HttpApi
          Properties:
            ApiId: !Ref TransadminApi
            Method: PUT
            Path: /notes/{id}
        Delete:
          Type: HttpApi
          Properties:
            ApiId: !Ref TransadminApi
            Method: DELETE
            Path: /notes/{id}
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable

Outputs:
  TransadminApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${TransadminApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}
