version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "transadmin-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17s1l408xtmsa"
s3_prefix = "transadmin-test"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = 'ProjectName="transadmin" Environment="test"'