AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  DeleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete-note/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /delete-note
            Method: delete

Outputs:
  TransadminApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete-note'
  DeleteNoteFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt DeleteNoteFunction.Arn
  DeleteNoteFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt DeleteNoteFunction.Arn
