Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs12.x
    Timeout: 5

Resources:
  GetNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-notes
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /get-notes
            Method: get

  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create-note
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /create-note
            Method: delete

  DeleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete-note
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /delete-note
            Method: delete

Outputs:
  DeleteNoteFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt DeleteNoteFunction.Arn
  DeleteNoteFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt DeleteNoteFunction.Arn
