default:
    type: postgres
    host: ubuntu
    port: 5432
    username: transadmin
    password: password
    database: transadmin
    synchronize: true
    logging: true
    entities: [src/entities/*.ts]
