default:
    type: postgres
    host: salt.db.elephantsql.com
    port: 5432
    username: uydgpbxs
    password: B4OjpwsWagVpk73Nps3iigixZrRfHy_A
    database: uydgpbxs
    synchronize: true
    logging: false
    entities: [src/entities/*.ts]
