name: sam deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: aws
        run: pip install aws-sam-cli

      - uses: actions/checkout@v2

      - name: build
        run: cd backend && npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: build
        run: sam deploy --stack-name transadmin-prod --s3-bucket ${{ secrets.SAM_S3_BUCKET }} --s3-prefix transadmin --capabilities CAPABILITY_NAMED_IAM
