name: sam deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for versions
        run: npm --version; node --version

      - name: list files
        run: cd backendv2 && ls -la

      - name: aws
        run: aws --version

      - name: python
        run: python --version

      - name: pip
        run: pip --version
